
export const BLOOD_TEST_RANGES: Record<string, { min: number, max: number, unit: string, label: string }> = {
    'calcium': { min: 8.5, max: 10.5, unit: 'mg/dL', label: 'Calcium(칼슘)' },
    'inorganic_p': { min: 2.5, max: 4.2, unit: 'mg/dL', label: 'Inorganic P(인)' },
    'glucose': { min: 70, max: 110, unit: 'mg/dL', label: 'Glucose(혈당)' },
    'bun': { min: 8.5, max: 22, unit: 'mg/dL', label: 'BUN(혈액요소질소)' },
    'creatinine': { min: 0.68, max: 1.19, unit: 'mg/dL', label: 'Creatinine(크레아티닌)' },
    'uric_acid': { min: 3.5, max: 8.1, unit: 'mg/dL', label: 'Uric Acid(요산)' },
    'total_cholesterol': { min: 142, max: 240, unit: 'mg/dL', label: 'Total cholesterol(총콜레스테롤)' },
    'total_protein': { min: 6.0, max: 8.0, unit: 'g/dL', label: 'Total Protein(총 단백)' },
    'albumin': { min: 3.3, max: 5.3, unit: 'g/dL', label: 'Albumin(알부민)' },
    'alk_phos': { min: 50, max: 151, unit: 'IU/L', label: 'Alk. Phos(알칼리인산분해효소)' },
    'ast': { min: 13.0, max: 34.0, unit: 'IU/L', label: 'AST(GOT)' },
    'alt': { min: 5.0, max: 46.0, unit: 'IU/L', label: 'ALT(GPT)' },
    't_bilirubin': { min: 0.5, max: 1.8, unit: 'mg/dL', label: 'T. Bilirubin(총 빌리루빈)' },
    'gamma_gt': { min: 12.0, max: 54.0, unit: 'IU/L', label: 'Gamma-GT(감마글루타밀 전이효소)' },
    'na': { min: 135.0, max: 145.0, unit: 'mmol/L', label: 'Na(나트륨)' },
    'k': { min: 3.5, max: 5.5, unit: 'mmol/L', label: 'K(칼륨)' },
    'cl': { min: 98, max: 110, unit: 'mmol/L', label: 'Cl(염화물)' },
    'amylase': { min: 30, max: 115, unit: 'U/L', label: 'Amylase(아밀라아제)' },
    'lipase': { min: 5.0, max: 60.0, unit: 'U/L', label: 'Lipase(지질분해효소)' },
    'wbc_count': { min: 4.0, max: 10.8, unit: '10^3/uL', label: 'WBC COUNT(백혈구수)' },
    'rbc_count': { min: 3.6, max: 6.1, unit: '10^6/uL', label: 'RBC COUNT(적혈구수)' },
    'hemoglobin': { min: 13.0, max: 17.4, unit: 'g/dL', label: 'Hemoglobin(혈색소)' },
    'hct': { min: 40.0, max: 52.0, unit: '%', label: 'Hct(적혈구 용적율)' },
    'neutrophil': { min: 1.7, max: 7, unit: '10^3/uL', label: 'Neutrophil(#)(중성구)' },
    'cea': { min: 0.0, max: 5.0, unit: 'ng/mL', label: 'CEA(암종 태아성 항원)' },
    'ca_19_9': { min: 0, max: 35, unit: 'U/mL', label: 'CA 19-9' },
}
